# Generated by Django 4.2.17 on 2025-03-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biotrack',
            name='password',
            field=models.CharField(default=1, max_length=255, verbose_name='Password'),
        ),
    ]
