# Generated by Django 4.2.17 on 2025-03-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_alter_biotrack_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marktrack',
            old_name='arrival',
            new_name='checkTime',
        ),
        migrations.AddField(
            model_name='marktrack',
            name='checkType',
            field=models.CharField(default=1, max_length=255, verbose_name='IN or OUT'),
            preserve_default=False,
        ),
    ]
