# Generated by Django 4.2.17 on 2025-03-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0003_rename_arrival_marktrack_checktime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marktrack',
            name='checkTime',
            field=models.DateTimeField(null=True, verbose_name='Время прихода персоны'),
        ),
    ]
