# Generated by Django 4.2.17 on 2025-03-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_biotrack_department_remove_branch_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival', models.TimeField(verbose_name='Время прихода')),
                ('leaving', models.TimeField(verbose_name='Время Ухода')),
            ],
            options={
                'verbose_name': 'Часы Работы',
                'verbose_name_plural': 'Часы Работы',
            },
        ),
        migrations.AlterModelOptions(
            name='biotrack',
            options={'verbose_name': 'Био Трек', 'verbose_name_plural': 'Био Треки'},
        ),
    ]
