# Generated by Django 4.2.17 on 2025-03-05 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_workhours_alter_biotrack_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='organization',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
            preserve_default=False,
        ),
    ]
