# Generated by Django 4.2.17 on 2025-03-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_marktrack_remove_workhours_arrival_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marktrack',
            name='arrival',
            field=models.TimeField(null=True, verbose_name='Время прихода персоны'),
        ),
        migrations.AlterField(
            model_name='marktrack',
            name='leaving',
            field=models.TimeField(null=True, verbose_name='Время Ухода персоны'),
        ),
        migrations.AlterField(
            model_name='workhours',
            name='arrive',
            field=models.TimeField(null=True, verbose_name='Время прихода'),
        ),
        migrations.AlterField(
            model_name='workhours',
            name='leave',
            field=models.TimeField(null=True, verbose_name='Время Ухода'),
        ),
    ]
