# Generated by Django 4.2.17 on 2025-03-05 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_alter_marktrack_arrival_alter_marktrack_leaving_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MarkTrack',
        ),
    ]
