# Generated by Django 4.2.17 on 2025-03-17 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_delete_marktrack'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BioTrack',
        ),
    ]
