# Generated by Django 4.2.17 on 2025-03-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0011_delete_biotrack'),
    ]

    operations = [
        migrations.AddField(
            model_name='workhours',
            name='title',
            field=models.CharField(default=1, max_length=255, verbose_name='Название филиала'),
            preserve_default=False,
        ),
    ]
