# Generated by Django 4.2.17 on 2025-03-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0012_workhours_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workhours',
            old_name='title',
            new_name='schName',
        ),
        migrations.RemoveField(
            model_name='workhours',
            name='arrive',
        ),
        migrations.RemoveField(
            model_name='workhours',
            name='leave',
        ),
        migrations.AddField(
            model_name='workhours',
            name='EndTime',
            field=models.DateTimeField(default=None, null=True, verbose_name='Время Ухода'),
        ),
        migrations.AddField(
            model_name='workhours',
            name='StartTime',
            field=models.DateTimeField(default=None, null=True, verbose_name='Время прихода'),
        ),
    ]
