# Generated by Django 4.2.17 on 2025-03-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0013_rename_title_workhours_schname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='departmentTitle',
            new_name='deptName',
        ),
        migrations.RemoveField(
            model_name='department',
            name='id',
        ),
        migrations.AddField(
            model_name='department',
            name='deptID',
            field=models.BigAutoField(default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
