# Generated by Django 4.2.17 on 2025-03-24 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0015_department_id_alter_department_deptid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='deptID',
        ),
    ]
