# Generated by Django 4.2.17 on 2025-03-05 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_biotrack_department_remove_branch_level_and_more'),
        ('accounts', '0002_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birthday',
        ),
        migrations.CreateModel(
            name='NaturalPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnf', models.IntegerField(unique=True, verbose_name='ПИНФЛ')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.branch')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.department')),
                ('jobTitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.jobtitle')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
        ),
    ]
