# Generated by Django 5.2 on 2025-05-12 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_naturalperson_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logsms',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
