# Generated by Django 5.2 on 2025-05-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_phone_number_logsms_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='naturalperson',
            name='is_department_head',
            field=models.BooleanField(default=False),
        ),
    ]
