# Generated by Django 4.2.17 on 2025-03-05 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_birthday_naturalperson'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='naturalperson',
            options={'verbose_name': 'Персона', 'verbose_name_plural': 'Люди'},
        ),
    ]
