# Generated by Django 4.2.17 on 2025-03-05 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_workhours_alter_biotrack_options'),
        ('accounts', '0004_alter_naturalperson_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='naturalperson',
            name='work_hours',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='organizations.workhours'),
            preserve_default=False,
        ),
    ]
