# Generated by Django 4.2.17 on 2025-03-05 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_naturalperson_work_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='naturalperson',
            name='work_hours',
        ),
    ]
