# Generated by Django 4.2.17 on 2025-03-05 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_naturalperson_work_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival', models.TimeField(null=True, verbose_name='Время прихода персоны')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.naturalperson')),
            ],
        ),
    ]
