# Generated by Django 4.2.17 on 2025-03-17 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_marktrack'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MarkTrack',
        ),
    ]
