# Generated by Django 4.2.17 on 2025-03-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_delete_marktrack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naturalperson',
            name='pnf',
            field=models.IntegerField(blank=True, default=12345, null=True, verbose_name='ПИНФЛ'),
        ),
    ]
