# Generated by Django 4.2.17 on 2025-03-24 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0016_remove_department_deptid'),
        ('accounts', '0010_alter_naturalperson_pnf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naturalperson',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.branch'),
        ),
        migrations.AlterField(
            model_name='naturalperson',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.department'),
        ),
        migrations.AlterField(
            model_name='naturalperson',
            name='jobTitle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.jobtitle'),
        ),
        migrations.AlterField(
            model_name='naturalperson',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='naturalperson',
            name='work_hours',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.workhours'),
        ),
    ]
