# Generated by Django 5.2 on 2025-04-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_user_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='naturalperson',
            name='about',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='О себе'),
        ),
    ]
