# Generated by Django 5.2 on 2025-04-30 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_naturalperson_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naturalperson',
            name='about',
            field=models.TextField(blank=True, help_text='Расскажите о себе, своих интересах и опыте', max_length=1000, null=True, verbose_name='О себе'),
        ),
    ]
