# Generated by Django 5.2 on 2025-05-02 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_naturalperson_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='naturalperson',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='natural_person', to=settings.AUTH_USER_MODEL),
        ),
    ]
