# Generated by Django 5.2 on 2025-05-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_naturalperson_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='naturalperson',
            name='email',
            field=models.EmailField(default=998971235467, max_length=235, verbose_name='Электронная почта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='naturalperson',
            name='phone',
            field=models.CharField(default='998971235467', max_length=13),
            preserve_default=False,
        ),
    ]
